export const handleErrors = (err) => {
  console.log("Controlled error: ", err);
};
